src/liqcanvas_firstrun_splash.c File Reference
Run liqcell events.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <dirent.h>
#include `liqbase.h`
#include `liqcell.h`
#include `liqcell_easyrun.h`
#include `liqcell_easypaint.h`
#include `vgraph.h`
Functions
int liqcanvas_firstrun_splash ()
Detailed Description
Run liqcell events.
Author: Gary Birkett Copyright (C) 2008 Gary Birkett
LICENSE
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Function Documentation
int liqcanvas_firstrun_splash ()
first run `splash screen` designed to be used in the middle of firstrun detection logic to automagically remove glitches :)
Returns: Success or Failure
References liqapp_GetTicks(), and liqapp_log().
Referenced by liqcanvas_init().