src/liqcanvas.c File Reference
Basic Canvas control functions.
#include <stdlib.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Xatom.h>
#include <X11/extensions/Xv.h>
#include <X11/extensions/Xvlib.h>
#include `liqapp.h`
#include `liqimage.h`
#include `liqcanvas.h`
#include `liqcliprect.h`
#include `liqx11info.h`
Functions
int liqcanvas_firstrun_splash ()
liqx11info * liqcanvas_getx11info ()
int liqcanvas_nextevent_x11 (LIQEVENT *ev, int *dirtyflagptr)
int liqcanvas_takepicture ()
int liqcanvas_isopen ()
int liqcanvas_init_usecustomwindow (int pixelwidth, int pixelheight, void *customx11display, void *customx11window)
int liqcanvas_init_inner (int pixelwidth, int pixelheight, int fullscreen)
int liqcanvas_init (int pixelwidth, int pixelheight, int fullscreen)
int liqcanvas_close ()
liqcliprect * liqcanvas_getcliprect ()
liqimage * liqcanvas_getsurface ()
int liqcanvas_getwidth ()
int liqcanvas_getheight ()
int liqcanvas_getdpix ()
int liqcanvas_getdpiy ()
float liqcanvas_getscalew ()
float liqcanvas_getscaleh ()
int liqcanvas_eventcount ()
int liqcanvas_nextevent (LIQEVENT *ptrevent, int *dirtyflagptr)
int liqcanvas_refreshdisplay ()
int liqcanvas_minimize ()
Variables
liqcanvas canvas = {0,0}
liqx11info x11infobase = {NULL}
Detailed Description
Basic Canvas control functions.
Author: Gary Birkett Copyright (C) 2008 Gary Birkett
LICENSE
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Function Documentation
int liqcanvas_firstrun_splash ()
first run `splash screen` designed to be used in the middle of firstrun detection logic to automagically remove glitches :)
Returns: Success or Failure
References liqapp_GetTicks(), and liqapp_log().
Referenced by liqcanvas_init().
int liqcanvas_init (int pixelwidth, int pixelheight, int fullscreen)
Construct a canvas with a given height and width, also with the option of going fullscreen.
Parameters:
pixelwidth Width of the canvas
pixelheight Height of the canvas
fullscreen Set this to 1 in order to have a fullscreen canvas
Returns: int 0 for success, -1 for error/failure
References liqapp_errorandfail(), liqapp_log(), liqcanvas_firstrun_splash(), and liqcanvas_init_inner().
int liqcanvas_init_inner (int pixelwidth, int pixelheight, int fullscreen)
Construct a canvas with a given height and width, also with the option of going fullscreen.
Parameters:
pixelwidth Width of the canvas
pixelheight Height of the canvas
fullscreen Set this to 1 in order to have a fullscreen canvas
Returns: int 0 for success, -1 for error/failure
References liqapp_errorandfail(), and liqapp_log().
Referenced by liqcanvas_init().