src/liqcell_easyrun.c File Reference
Run liqcell events.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <dirent.h>
#include `liqbase.h`
#include `liqcell.h`
#include `liqcell_prop.h`
#include `liqcell_easyrun.h`
#include `liqcell_easypaint.h`
#include `vgraph.h`
Data Structures
struct vrect
Functions
int vrect_ensurepositive (vrect *self)
int vrect_scaletofit (vrect *self, vrect *avail, vrect *required)
float calcaspect (int captionw, int captionh, int availw, int availh)
liqcell * liqcell_easyhittest (liqcell *self, int mx, int my, int *hitx, int *hity)
liqcell * toolclick (liqcell *vis)
liqcell * liqcell_findnexthandler (liqcell *self, liqcell *root, char *handlername)
liqcell * liqcell_findfirsthandler (liqcell *root, char *handlername)
int liqcell_easyrun (liqcell *self)
Variables
int liqcell_showdebugboxes
int liqcell_easyrun_depth = 0
Detailed Description
Run liqcell events.
Author: Gary Birkett Copyright (C) 2008 Gary Birkett
LICENSE
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Function Documentation
int liqcell_easyrun (liqcell * self)
Main program event handler.
Parameters:
self The liqcell to run
Returns: Success or Failure
References liqapp_fps(), liqapp_GetTicks(), liqapp_log(), liqapp_sleep(), liqcell_getcaption(), liqcell_getlinknext(), liqcell_getlinkparent(), liqcell_getlinkprev(), liqcell_getname(), liqcell_getqualifiedname(), liqcell_handlerfind(), liqcell_handlerrun(), and liqcell_print2().