src/liqcell_dllcache.c File Reference
This file is the master file which loads and manages all dynamic widgets in the subdirectory.
#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>
#include <elf.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <dirent.h>
#include <pthread.h>
#include `liqcell.h`
#include `liqcell_dllcache.h`
Functions
int dllcache_init ()
int dllcache_close ()
int dllcache_scan_dllfile (char *dll_filename)
int dllcache_scan_folder (char *widgetpath)
int dllcache_scan ()
liqcell * dllcache_runconstructorinner (char *classname)
liqcell * dllcache_runconstructor (char *classname)
dllcacheitem * dllcache_getbase ()
int dllcache_getsize ()
int dllcache_getused ()
Detailed Description
This file is the master file which loads and manages all dynamic widgets in the subdirectory.
Author: Gary Birkett Copyright (C) 2008 Gary Birkett
LICENSE
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Function Documentation
int dllcache_close ()
free the cache
int dllcache_init ()
prepare the cache
References liqapp_warnandcontinue().
Referenced by dllcache_scan().
liqcell* dllcache_runconstructor (char * classname)
run a specified constructor and return the result
References dllcache_scan(), liqapp_log(), and liqapp_warnandcontinue().
int dllcache_scan ()
scan the files to initialize the cache
References dllcache_init(), and liqapp_warnandcontinue().
Referenced by dllcache_runconstructor().