src/liqcell_mk_star.c File Reference
small cell building helper functions
#include `liqcell.h`
#include `liqcell_easyrun.h`
#include `liqcell_prop.h`
#include `liqcell_mk_star.h`
Functions
liqcell * mkmeta_group (liqcell *first,...)
liqcell * mkmeta_title (char *key)
liqcell * mkmeta_author (char *key)
liqcell * mkmeta_description (char *key)
liqcell * mkmeta_version (char *key)
liqcell * mkgroupa (char *key, char *classname, liqcell *first, va_list arg)
liqcell * mkgroup (char *key, liqcell *first,...)
Detailed Description
small cell building helper functions
Author: Gary Birkett Copyright (C) 2008 Gary Birkett
LICENSE
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Function Documentation
liqcell* mkgroup (char * key, liqcell * first, ...)
construct a group of cells based on ...
References mkgroup(), and mkgroupa().
Referenced by mkgroup().
liqcell* mkgroupa (char * key, char * classname, liqcell * first, va_list arg)
construct a group of non visual cells based on a va_list
References mkgroupa().
Referenced by mkgroup(), mkgroupa(), and mkmeta_group().
liqcell* mkmeta_author (char * key)
construct a meta_description element
liqcell* mkmeta_description (char * key)
construct a meta_description element
liqcell* mkmeta_group (liqcell * first, ...)
construct a meta_info group based on ...
References mkgroupa().
liqcell* mkmeta_title (char * key)
construct a meta_title element
liqcell* mkmeta_version (char * key)
construct a meta_version element