src/liqui.c File Reference
Libliqbase User Interface Functions.
#include <string.h>
#include <stdlib.h>
#include `liqui.h`
#include `liqcell.h`
#include `liqcell_prop.h`
#include `liqcell_easyrun.h`
#include `liqbase.h`
Functions
liqcell * uititlebar_create (char *key, char *title, char *description)
liqcell * uiinfobar_create (char *infotext)
liqcell * uitextbox_create (char *caption, char *datadefault)
liqcell * textbox_create ()
liqcell * uinumberbox_create (char *caption, char *datadefault)
liqcell * uipicturebox_create (char *caption, char *datadefault)
liqcell * liqui_create ()
Detailed Description
Libliqbase User Interface Functions.
Author: Gary Birkett Copyright (C) 2008 Gary Birkett
LICENSE
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Function Documentation
liqcell* textbox_create ()
Create a textbox ui component
Returns: liqcell* The new textbox
References liqcell_handleradd(), liqcell_propseti(), liqcell_propsets(), and liqcell_setfont().
liqcell* uiinfobar_create (char * infotext)
Create a infobar ui component
Parameters:
infotext Caption of the bar
Returns: liqcell* The new infobar
References liqcell_handleradd(), liqcell_propsets(), liqcell_setcaption(), and liqcell_setfont().
liqcell* uinumberbox_create (char * caption, char * datadefault)
Create a numberbox ui component
Parameters:
caption The caption
datafefault Data caption
Returns: liqcell* The new numberbox
References liqcell_propsets(), liqcell_setcaption(), and liqcell_setfont().
liqcell* uipicturebox_create (char * caption, char * datadefault)
Create a picturebox ui component
Parameters:
caption The caption
datafefault Data caption
Returns: liqcell* The new picturebox
References liqcell_propsets(), liqcell_setcaption(), liqcell_setfont(), and liqcell_setimage().
liqcell* uitextbox_create (char * caption, char * datadefault)
Create a textbox ui component, this is the development function
Parameters:
caption Body Caption
datadefault Caption of the data
Returns: liqcell* The new textbox
References liqcell_handleradd(), liqcell_propsets(), liqcell_setcaption(), and liqcell_setfont().
liqcell* uititlebar_create (char * key, char * title, char * description)
Create a titlebar ui component
Parameters:
key Name of the widget
title Title to display
description Describe what this titlebar is for
Returns: liqcell* The new titlebar
References liqcell_propseti(), liqcell_propsets(), liqcell_setcaption(), liqcell_setfont(), and liqcell_setimage().